### ISSUE TITLE
Missing null checks

### ISSUE THREAD

**Issue by NFM-8** [elisaautomate/kafka-connect-snmp#9]
In the connector code, there are several places where input is not checked against null, leading to null pointer exeption crashes.

I have test cases and can create a PR that fixes those, if you are interrested in.

**Comment by johannessarpola** [comment]
Thank you for the comments, I'm closing this ticket for now for inactivity. I've fixed at least few potential vectors for NPEs in the pull requests #15 and #14 and improved test coverage. However if you find ways to improve the software regarding these cases we're happy to receive PRs for test cases or improvements.
